version: 2.1

orbs:
   win: circleci/windows@1.0.0

workflows:
  version: 2
  build_all:
    jobs:
      - build-linux
      - build-osx

jobs:
  build-linux:
    docker:
      - image: ldcircleci/ld-c-sdk-ubuntu  # defined in sdks-ci-docker project
    steps:
      - checkout
      - run:
          name: Fetch SDK
          command: unzip artifacts/linux-gcc-64bit-static.zip
      - run:
          name: Build Hello
          command: ./build-linux.sh

  build-osx:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Fetch SDK
          command: unzip artifacts/osx-clang-64bit-static.zip
      - run:
          name: Build Hello
          command: ./build-mac.sh
