version: 2.1

orbs:
   win: circleci/windows@1.0.0

workflows:
  version: 2
  build_all:
    jobs:
      - build-linux
      - build-osx
      - build-windows

jobs:
  build-linux:
    docker:
      - image: ldcircleci/ld-c-sdk-ubuntu  # defined in sdks-ci-docker project
    steps:
      - checkout
      - run:
          name: Fetch SDK
          command: unzip artifacts/linux-gcc-64bit-static.zip
      - run:
          name: Build Hello
          command: ./build-linux.sh

  build-osx:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Fetch SDK
          command: unzip artifacts/osx-clang-64bit-static.zip
      - run:
          name: Build Hello
          command: ./build-mac.sh

  build-windows:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Fetch SDK
          command: |
              $ProgressPreference = "SilentlyContinue"  # prevents console errors from CircleCI host
              Expand-Archive -Path artifacts\windows-vs-64bit-dynamic.zip -DestinationPath .
      - run:
          name: Build Hello
          command: .\build-windows.ps1
